_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
#_acme_demo:
#    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

create_product:
    path:    /create
    defaults:    { _controller:AcmeStoreBundle:Default:create }
find:
    path:    /show/{id}
    defaults:    { _controller:AcmeStoreBundle:Default:show }
new_article:
    path:   /articles/new
    defaults:    { _controller:ForbessArticlesBundle:Default:new }
index_articles:
    pattern: /
    defaults:    { _controller:ForbessArticlesBundle:Default:index }
